version: '3.3'

services:

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
     - 3457:6379  
    volumes:
      - ./todo-backend/redis_data:/data 

  todo-backend:                    # The name of the service, can be anything
    image: todo-backend # Declares which image to use
    build: ./todo-backend/  # The context will pick this directory as the "build context" 
    ports:                # Declares the ports to publish
      - 3001:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
    container_name: todo-backend-full # This will name the container todo-frontend

  todo-frontend:
    image: todo-frontend
    build: ./todo-frontend/ 
    ports:
      - 3000:80 
    container_name: todo-frontend-full # This will name the container todo-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-full